common: &default_settings
  license_key: '<%= ENV['NEWRELIC_KEY'] %>'
  app_name: Heartbeat

development:
  <<: *default_settings
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true
